version: '2'
services:
  jwtjob-app:
    image: jwtjob
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=jwtjob-cassandra
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jwtjob-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: jwtjob-cassandra
  jwtjob-cassandra-node:
    image: cassandra:3.11.5
    environment:
      - CASSANDRA_SEEDS=jwtjob-cassandra
  jwtjob-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: jwtjob-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
